FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy server files and data directory
COPY src/server.js ./src/
COPY data ./data

# Expose port 3001
EXPOSE 3001

# Start server
CMD ["node", "src/server.js"]
