import React, { useState } from 'react';
import './PolarDataTable.css';
import {
  Paper, Typography, Box, Table, TableBody, TableCell,
  TableContainer, TableHead, TableRow, IconButton,
  TextField, Button, FormControl, InputLabel, Select,
  MenuItem, Divider, Dialog, DialogTitle, DialogContent,
  DialogActions
} from '@mui/material';
import { Edit, Delete, Save, Cancel, Add, Download } from '@mui/icons-material';

const PolarDataTable = ({ 
  data, 
  windSpeed, 
  availableWindSpeeds,
  onChangeWindSpeed,
  onUpdateBoatSpeed, 
  onAddAngleEntry, 
  onDeleteAngleEntry,
  onAddWindSpeed,
  onDeleteWindSpeed
}) => {
  const [newAngle, setNewAngle] = useState('');
  const [newSpeed, setNewSpeed] = useState('');
  const [editingCell, setEditingCell] = useState(null);
  const [editValue, setEditValue] = useState('');
  const [newWindSpeed, setNewWindSpeed] = useState('');
  const [showAddWindSpeedDialog, setShowAddWindSpeedDialog] = useState(false);

  const handleAddEntry = (e) => {
    e.preventDefault();
    const angleValue = parseInt(newAngle, 10);
    const speedValue = parseFloat(newSpeed);
    
    if (isNaN(angleValue) || isNaN(speedValue)) {
      alert('Please enter valid numbers');
      return;
    }
    
    if (angleValue < 0 || angleValue > 180) {
      alert('Angle must be between 0 and 180 degrees');
      return;
    }
    
    if (speedValue < 0) {
      alert('Boat speed cannot be negative');
      return;
    }
    
    onAddAngleEntry(angleValue, speedValue);
    setNewAngle('');
    setNewSpeed('');
  };

  const handleAddWindSpeed = (e) => {
    e.preventDefault();
    const speedValue = parseInt(newWindSpeed, 10);
    
    if (isNaN(speedValue) || speedValue <= 0) {
      alert('Please enter a valid positive number');
      return;
    }
    
    onAddWindSpeed(speedValue);
    setNewWindSpeed('');
    setShowAddWindSpeedDialog(false);
  };

  const handleDeleteWindSpeed = () => {
    if (window.confirm(`Are you sure you want to delete wind speed ${windSpeed} knots?`)) {
      onDeleteWindSpeed(windSpeed);
    }
  };

  const startEditing = (angle, currentSpeed) => {
    setEditingCell(angle);
    setEditValue(currentSpeed.toString());
  };

  const saveEdit = () => {
    const speedValue = parseFloat(editValue);
    if (isNaN(speedValue) || speedValue < 0) {
      alert('Please enter a valid positive number');
      return;
    }
    
    onUpdateBoatSpeed(editingCell, speedValue);
    setEditingCell(null);
  };

  const cancelEdit = () => {
    setEditingCell(null);
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') {
      saveEdit();
    } else if (e.key === 'Escape') {
      cancelEdit();
    }
  };

  return (
    <Paper elevation={2} sx={{ p: 3 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
        <IconButton 
          color="success"
          onClick={() => {
            // Generate polar file content
            let fileContent = "! Polar data file generated by Polar Chart App\n";
            fileContent += "! Format: Wind Speed, followed by pairs of Angle and Boat Speed\n";
            fileContent += `! Created: ${new Date().toISOString().split('T')[0]}\n`;
            
            // Create a blob and download link
            const blob = new Blob([fileContent], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'polar_data.pol';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
          }}
          title="Download polar data"
        >
          <Download />
        </IconButton>
        <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
          <FormControl size="small" sx={{ minWidth: 200 }}>
            <InputLabel id="edit-wind-speed-label">Editing Wind Speed</InputLabel>
            <Select
              labelId="edit-wind-speed-label"
              id="edit-wind-speed"
              value={windSpeed}
              label="Editing Wind Speed"
              onChange={(e) => onChangeWindSpeed(Number(e.target.value))}
            >
              {availableWindSpeeds.map(speed => (
                <MenuItem key={speed} value={speed}>{speed} knots</MenuItem>
              ))}
            </Select>
          </FormControl>
          <IconButton 
            size="small" 
            color="success" 
            onClick={() => setShowAddWindSpeedDialog(true)}
            title="Add new wind speed"
          >
            <Add fontSize="small" />
          </IconButton>
          <IconButton 
            size="small" 
            color="error" 
            onClick={handleDeleteWindSpeed}
            disabled={availableWindSpeeds.length <= 1}
            title="Delete current wind speed"
          >
            <Delete fontSize="small" />
          </IconButton>
        </Box>
      </Box>
            
      <TableContainer sx={{ mb: 3 }}>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>Angle (°)</TableCell>
              <TableCell sx={{ width: '120px' }}>BSP (knots)</TableCell>
              <TableCell align="right">Actions</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {data.filter(item => item.isAnchor).map((item) => (
              <TableRow key={item.angle} sx={{ '&:last-child td, &:last-child th': { border: 0 } }}>
                <TableCell component="th" scope="row">
                  {item.angle}°
                </TableCell>
                <TableCell>
                  {editingCell === item.angle ? (
                    <TextField
                      type="number"
                      size="small"
                      inputProps={{ 
                        step: "0.1",
                        min: "0"
                      }}
                      value={editValue}
                      onChange={(e) => setEditValue(e.target.value)}
                      onKeyDown={handleKeyDown}
                      autoFocus
                      sx={{ width: '100px' }}
                    />
                  ) : (
                    <Typography 
                      variant="body2" 
                      sx={{ cursor: 'pointer', '&:hover': { bgcolor: 'action.hover', borderRadius: 1, p: 0.5 } }}
                      onClick={() => startEditing(item.angle, item.boatSpeed)}
                    >
                      {item.boatSpeed}
                    </Typography>
                  )}
                </TableCell>
                <TableCell align="right">
                  {editingCell === item.angle ? (
                    <>
                      <IconButton size="small" color="primary" onClick={saveEdit} title="Save">
                        <Save fontSize="small" />
                      </IconButton>
                      <IconButton size="small" color="error" onClick={cancelEdit} title="Cancel">
                        <Cancel fontSize="small" />
                      </IconButton>
                    </>
                  ) : (
                    <>
                      <IconButton 
                        size="small" 
                        color="primary" 
                        onClick={() => startEditing(item.angle, item.boatSpeed)}
                        title="Edit"
                      >
                        <Edit fontSize="small" />
                      </IconButton>
                      <IconButton 
                        size="small" 
                        color="error" 
                        onClick={() => onDeleteAngleEntry(item.angle)}
                        disabled={item.angle === 0 || item.angle === 180}
                        title="Delete"
                      >
                        <Delete fontSize="small" />
                      </IconButton>
                    </>
                  )}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
      
      <Divider sx={{ my: 2 }} />
      
      <Box component="form" onSubmit={handleAddEntry} sx={{ mt: 3 }}>
        <Typography variant="h6" component="h3" gutterBottom>
          Add New Angle Entry
        </Typography>
        
        <Box sx={{ display: 'flex', flexDirection: { xs: 'column', sm: 'row' }, gap: 2, mb: 2, width:'100%' }}>
          <TextField
            label="Angle (°)"
            value={newAngle}
            onChange={(e) => setNewAngle(e.target.value)}
            required
            fullWidth
          />
          
          <TextField
            label="BSP (kt)"
            value={newSpeed}
            onChange={(e) => setNewSpeed(e.target.value)}
            required
            fullWidth
          />
        </Box>
        
        <Button 
          type="submit" 
          variant="contained" 
          color="primary"
        >
          Add Angle Entry
        </Button>
      </Box>

      
      {/* Add Wind Speed Dialog */}
      <Dialog open={showAddWindSpeedDialog} onClose={() => setShowAddWindSpeedDialog(false)}>
        <DialogTitle>Add New Wind Speed</DialogTitle>
        <form onSubmit={handleAddWindSpeed}>
          <DialogContent>
            <TextField
              autoFocus
              margin="dense"
              label="Wind Speed (knots)"
              type="number"
              fullWidth
              variant="outlined"
              value={newWindSpeed}
              onChange={(e) => setNewWindSpeed(e.target.value)}
              inputProps={{ min: 1, step: 1 }}
              required
            />
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setShowAddWindSpeedDialog(false)} color="inherit">
              Cancel
            </Button>
            <Button type="submit" color="primary" variant="contained">
              Add
            </Button>
          </DialogActions>
        </form>
      </Dialog>
    </Paper>
  );
};

export default PolarDataTable;
